language: node_js
node_js:
  - "4.1"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  # install modules via browser ex)  jQuery
  - npm install -g bower
  - bower install

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - gulp uglify

notifications:
  email:
    recipients: 
      - kenji0x02@gmail.com
    on_success: change
    on_failure: always

